'use client';

import { motion } from 'framer-motion';
import { Bot, ChevronRight, ClipboardCheck, Zap, Download } from 'lucide-react';
import { useState } from 'react';

const dubaiGuides = [
  {
    title: 'Household Readiness',
    items: [
      'Store 3 days of bottled water (at least 4L/person/day in Dubai heat)',
      'Non-perishable food (dates, canned goods, energy bars)',
      'Battery-powered lantern + extra batteries',
      'First aid kit with oral rehydration salts',
      'Copies of Emirates ID, passport, and tenancy contract',
    ],
  },
  {
    title: 'Evacuation Protocol (Dubai)',
    items: [
      'Identify your nearest Dubai Civil Defence shelter',
      'Avoid underpasses and wadi crossings during heavy rain',
      'Follow RTA road closure alerts before driving',
      'Keep full tank of petrol — stations may close during alerts',
      'Register with Dubai Civil Defence emergency notification system',
    ],
  },
  {
    title: 'Heat Emergency Response',
    items: [
      'Move to AC environment immediately — malls, mosques, metro stations',
      'Call 998 (ambulance) if someone shows signs of heatstroke',
      'Outdoor work is legally banned 12–3 PM June–September',
      'Use cooling towels and avoid dark clothing in direct sun',
      'Check on workers and labourers in your area',
    ],
  },
  {
    title: 'Dust Storm (Haboob) Safety',
    items: [
      'Seal windows and doors — tape gaps if possible',
      'Turn off AC units that draw outside air',
      'Wear N95 mask if outdoors unavoidable',
      'Reduce speed to 40km/h max and turn on fog lights',
      'Pull off road safely if visibility drops below 50m',
    ],
  },
  {
    title: 'Digital Backup',
    items: [
      'Download offline UAE maps via Google Maps / Maps.me',
      'Save Dubai Civil Defence hotline: 997',
      'Screenshot emergency contacts and this plan',
      'External battery pack (min 20,000 mAh)',
      'WhatsApp family group with agreed check-in code',
    ],
  },
];

const printGuide = (guide: typeof dubaiGuides[number]) => {
  const win = window.open('', '_blank');
  if (!win) return;
  win.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <title>Aegis – ${guide.title} Plan · Dubai, UAE</title>
      <style>
        body { font-family: Arial, sans-serif; color: #000; background: #fff; padding: 32px; font-size: 13px; line-height: 1.6; max-width: 600px; margin: 0 auto; }
        h1 { font-size: 20px; font-weight: 900; text-transform: uppercase; margin-bottom: 4px; }
        .sub { font-size: 11px; opacity: 0.5; text-transform: uppercase; letter-spacing: 0.1em; margin-bottom: 24px; }
        ol { padding-left: 20px; }
        ol li { margin-bottom: 10px; }
        .footer { margin-top: 32px; font-size: 10px; opacity: 0.4; border-top: 1px solid #ddd; padding-top: 12px; }
      </style>
    </head>
    <body>
      <h1>${guide.title}</h1>
      <p class="sub">Aegis Climate Resilience · Dubai, UAE · ${new Date().toLocaleString('en-AE', { timeZone: 'Asia/Dubai' })}</p>
      <ol>${guide.items.map(item => `<li>${item}</li>`).join('')}</ol>
      <div class="footer">Generated by Aegis · WeatherWise Hack 2026 · Dubai Civil Defence compliant guidelines</div>
    </body>
    </html>
  `);
  win.document.close();
  setTimeout(() => win.print(), 400);
};

export const PreparednessAssistant = () => {
  const [activeGuide, setActiveGuide] = useState<number | null>(null);

  return (
    <div id="resilience" className="glass p-6 rounded-3xl border border-white/10">
      <div className="flex items-center gap-3 mb-6">
        <div className="p-2 bg-cyan-neon/10 rounded-lg">
          <Bot className="text-cyan-neon" size={20} />
        </div>
        <div>
          <h3 className="font-bold uppercase tracking-tighter">AI Preparedness Assistant</h3>
          <p className="text-[10px] text-cyan-neon font-bold uppercase tracking-widest">
            Dubai, UAE · Localised Guidance
          </p>
        </div>
      </div>

      <div className="space-y-3">
        {dubaiGuides.map((guide, i) => (
          <div key={i}>
            <button
              onClick={() => setActiveGuide(activeGuide === i ? null : i)}
              className="w-full flex items-center justify-between p-4 rounded-xl bg-white/5 border border-white/10 hover:border-cyan-neon/30 transition-all"
            >
              <div className="flex items-center gap-3">
                <ClipboardCheck
                  size={18}
                  className={activeGuide === i ? 'text-cyan-neon' : 'opacity-40'}
                />
                <span className="font-medium text-sm">{guide.title}</span>
              </div>
              <ChevronRight
                size={16}
                className={`transition-transform ${
                  activeGuide === i ? 'rotate-90 text-cyan-neon' : 'opacity-40'
                }`}
              />
            </button>

            {activeGuide === i && (
              <motion.div
                initial={{ height: 0, opacity: 0 }}
                animate={{ height: 'auto', opacity: 1 }}
                className="overflow-hidden"
              >
                <div className="p-4 mt-1 bg-cyan-neon/5 rounded-xl border border-cyan-neon/10 space-y-2">
                  {guide.items.map((item, j) => (
                    <div key={j} className="flex items-start gap-2 text-sm">
                      <div className="w-1.5 h-1.5 rounded-full bg-cyan-neon mt-2 shrink-0" />
                      <span className="opacity-80">{item}</span>
                    </div>
                  ))}
                  <div className="flex gap-2 mt-4">
                    <button
                      onClick={() => printGuide(guide)}
                      className="flex-1 py-2 bg-cyan-neon/10 hover:bg-cyan-neon/20 text-cyan-neon text-xs font-bold rounded-lg border border-cyan-neon/20 flex items-center justify-center gap-2 transition-all"
                    >
                      <Download size={13} />
                      Export PDF
                    </button>
                    <button
                      onClick={() => setActiveGuide(null)}
                      className="flex-1 py-2 bg-white/5 hover:bg-white/10 text-xs font-bold rounded-lg border border-white/10 flex items-center justify-center gap-2 transition-all"
                    >
                      <Zap size={13} />
                      Done
                    </button>
                  </div>
                </div>
              </motion.div>
            )}
          </div>
        ))}
      </div>

      <div className="mt-6 p-4 rounded-2xl bg-gradient-to-br from-cyan-neon/10 to-transparent border border-cyan-neon/20">
        <p className="text-xs italic opacity-70">
          💡 Aegis Analysis: Dubai sits at 5m above sea level with rapid-drain infrastructure. 
          Key vulnerability: underpass flooding during heavy rain events (&gt;25mm/hr). 
          Nearest high-ground shelter: Dubai Hills (38m elevation).
        </p>
      </div>
    </div>
  );
};
